### ISSUE TITLE
validateData.py: 403 Error Encountered on Localhost Request

### ISSUE THREAD

**Issue by kojix2** [cBioPortal/cbioportal#10429]
Received 403 Error from Localhost When Using validateData.py

I ran into an error when executing the following command:

```
python core/src/main/scripts/importer/validateData.py -s ../cbioportal-docker-compose/study/lgg_ucsf_2014 -v
```

Here's the error message I received:

```
DEBUG: -: Requesting info from portal at 'http://localhost:8080'
Traceback (most recent call last):
  File "/Users/kojix2/Java/cbioportal/core/src/main/scripts/importer/validateData.py", line 5132, in request_from_portal_api
    response.raise_for_status()
  File "/Users/kojix2/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: OK for url: http://localhost:8080/api/info

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kojix2/Java/cbioportal/core/src/main/scripts/importer/validateData.py", line 5674, in <module>
    exit_status = main_validate(parsed_args)
  File "/Users/kojix2/Java/cbioportal/core/src/main/scripts/importer/validateData.py", line 5647, in main_validate
    portal_instance = load_portal_info(server_url, logger)
  File "/Users/kojix2/Java/cbioportal/core/src/main/scripts/importer/validateData.py", line 5280, in load_portal_info
    parsed_json = request_from_portal_api(path, api_name, logger)
  File "/Users/kojix2/Java/cbioportal/core/src/main/scripts/importer/validateData.py", line 5134, in request_from_portal_api
    raise ConnectionError(
ConnectionError: Failed to fetch metadata from the portal at [http://localhost:8080/api/info]
```

**Comment by kojix2** [comment]
The problem was with Python's request utilizing a Proxy. 
By setting the NO_PROXY environment variable to exclude 'localhost', I was able to address the issue:

```
os.environ['NO_PROXY'] = 'localhost'
```
