### ISSUE TITLE
x vs y fails to load for some charts in GENIE

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#11117]
In GENIE, adding an x-vs-y plot of Cancer Type vs Age at Sequencing doesn't work:
![image](https://github.com/user-attachments/assets/f9a114ba-f108-4bee-91d8-0dec74745d84)

**Comment by onursumer** [comment]
Looks like we are not properly handling special values for violin plot data. I see this error in the logs.

```
java.lang.NumberFormatException: For input string: ">89"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[na:na]
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:na]
	at java.base/java.lang.Double.parseDouble(Double.java:792) ~[na:na]
	at org.cbioportal.service.impl.ViolinPlotServiceImpl.lambda$getClinicalViolinPlotData$3(ViolinPlotServiceImpl.java:88) ~[classes!/:6.0.6-SNAPSHOT]
```

**Comment by onursumer** [comment]
This also happens in the legacy code base. I guess we never properly handled special values (like `>89`) for the violin plot.

**Comment by alisman** [comment]
@onursumer is this RFC80?

**Comment by onursumer** [comment]
@alisman This is also broken in the production. Seems like we are not handling special values (like `>89`) properly in legacy.

**Comment by onursumer** [comment]
@alisman A simple fix would be to filter out those special values which we cannot easily convert to a number. It's not ideal because we will lose some data, but probably better than showing a broken plot.
