### ISSUE TITLE
Bulk Data Loading Broken After cBioPortal Database Upgrade to MySQL 8.0

### ISSUE THREAD

**Issue by forus** [cBioPortal/cbioportal#11138]
The cBioPortal loader relies heavily on `LOAD DATA LOCAL INFILE ` sql statement for so called `bulkLoad`, a performant load of data [code](https://github.com/cBioPortal/cbioportal-core/blob/fb81dc6271571ae5447b9f202bf3e8dc3131a0d5/src/main/java/org/mskcc/cbio/portal/dao/MySQLbulkLoader.java#L236). Multiple file types (clinical data, copy number segment data,...) have only this mode implemented.

CI for cbioportal started to fail as it tries to laod data before running e2e tests.

Change that causes CI to fail: https://github.com/cBioPortal/cbioportal-docker-compose/commit/ca521ded0f05a8df5f6349158e6b2f1de1863cd5#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055dR3

The error loader gives on mysql 8
```
 java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Loading local data is disabled; this must be enabled on both the client and server sides
at org.mskcc.cbio.portal.scripts.ImportClinicalData.run(ImportClinicalData.java:759)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportClinicalData.main(ImportClinicalData.java:779)
Caused by: org.mskcc.cbio.portal.dao.DaoException: Loading local data is disabled; this must be enabled on both the client and server sides
at org.mskcc.cbio.portal.dao.MySQLbulkLoader.loadDataFromTempFileIntoDBMS(MySQLbulkLoader.java:265)
at org.mskcc.cbio.portal.dao.MySQLbulkLoader.flushAll(MySQLbulkLoader.java:96)
at org.mskcc.cbio.portal.scripts.ImportClinicalData.importData(ImportClinicalData.java:208)
at org.mskcc.cbio.portal.scripts.ImportClinicalData.run(ImportClinicalData.java:714)
```

MySql seems to change default for `local_infile`
```
By default, [local_infile](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_local_infile) is disabled. (This is a change from previous versions of MySQL.)
```
https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html

**Comment by forus** [comment]
ah, I think this is one of the ways to fix it https://github.com/cBioPortal/cbioportal/pull/11125/files

**Comment by inodb** [comment]
@forus Thanks for reporting! This fixed it looks like: https://github.com/cBioPortal/cbioportal-docker-compose/commit/52e8ecb9fe98a88f21d86bb0ba33cbfe00ce4fa5
