### ISSUE TITLE
Importer fails to import example on the rc branch

### ISSUE THREAD

**Issue by kteague** [cBioPortal/cbioportal#1295]
I am trying to import using the new importer from the rc branch (updated as of May 25th, 2016).

I am using the new data import instructions (https://github.com/thehyve/cbioportal/wiki/Data-Loading) and am trying to import the kirc example data set (https://github.com/thehyve/cbioportal/wiki/data-examples).

When the importer runs I get a 404 for the api/genesaliases call.

The importer appears to make calls to the other API URLs successfully, but then hits the api/genesaliases and throws a 404.

Pretty stumped on this one as the source code looks like Spring is mapping all the URLs consistently and I don't see anything that indicates how other APIs URLs could work fine and how a 404 is thrown instead of some other kind of error message.

```
# metaImport.py -s /opt/install-parts/kirc/tcga/ -u http://localhost:8080/cbioportal
Starting validation...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during validation step:
Traceback (most recent call last):
  File "/var/cbioportal/core/src/main/scripts/importer/metaImport.py", line 84, in <module>
    exitcode = validateData.main_validate(args)
  File "/var/cbioportal/core/src/main/scripts/importer/validateData.py", line 2794, in main_validate
    portal_instance = load_portal_info(server_url, logger)
  File "/var/cbioportal/core/src/main/scripts/importer/validateData.py", line 2534, in load_portal_info
    parsed_json = request_from_portal_api(path, api_name, logger)
  File "/var/cbioportal/core/src/main/scripts/importer/validateData.py", line 2409, in request_from_portal_api
    msg=e.message))
IOError: Connection error for URL: http://localhost:8080/cbioportal/api/genesaliases. Administrator: please check if [http://localhost:8080/cbioportal/api/genesaliases] is accessible. Message: 404 Client Error: Not Found for url: http://localhost:8080/cbioportal/api/genesaliases
```

**Comment by kteague** [comment]
I have resolved my import issues by doing a clean re-install. I had problems importing with newer releases and had to go back to 1.0.3 install to get TCGA data to load successfully.
