### ISSUE TITLE
SQL error in the new implementation from sprint1

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1335]
A query with mutation data will trigger the following error in catalina.out.

```
SEVERE: Servlet.service() for servlet [portal] in context with path [/beta] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."CENTER" as "sequencingCenter",
        "mutation"."MUTATION_STATUS" as "mutati' at line 3
### The error may exist in org/cbioportal/persistence/mybatis/MutationMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select          "mutation"."CENTER" as "sequencingCenter",         "mutation"."MUTATION_STATUS" as "mutationStatus",         "mutation"."TUMOR_REF_COUNT" as "referenceReadCountTumor",         "mutation"."NORMAL_REF_COUNT" as "referenceReadCountNormal",         "mutation"."TUMOR_ALT_COUNT" as "variantReadCountTumor",         "mutation"."NORMAL_ALT_COUNT" as "variantReadCountNormal",         "mutation"."VALIDATION_STATUS" as "validationStatus",          "mutation_event"."MUTATION_TYPE" as "mutationEvent.mutationType",         "mutation_event"."PROTEIN_CHANGE" as "mutationEvent.aminoAcidChange",         "mutation_event"."FUNCTIONAL_IMPACT_SCORE" as "mutationEvent.functionalImpactScore",         "mutation_event"."LINK_XVAR" as "mutationEvent.xvarLink",         "mutation_event"."LINK_PDB" as "mutationEvent.xvarLinkPdb",         "mutation_event"."LINK_MSA" as "mutationEvent.xvarLinkMsa",         "mutation_event"."CHR" as "mutationEvent.chr",         "mutation_event"."START_POSITION" as "mutationEvent.startPosition",         "mutation_event"."END_POSITION" as "mutationEvent.endPosition",         "mutation_event"."ONCOTATOR_PROTEIN_POS_START" as "mutationEvent.proteinStartPosition",         "mutation_event"."ONCOTATOR_PROTEIN_POS_END" as "mutationEvent.proteinEndPosition",         "mutation_event"."REFERENCE_ALLELE" as "mutationEvent.referenceAllele",         "mutation_event"."TUMOR_SEQ_ALLELE" as "mutationEvent.variantAllele",          "gene"."HUGO_GENE_SYMBOL" as "gene.hugoGeneSymbol",         "gene"."ENTREZ_GENE_ID" as "gene.entrezGeneId",          "sample"."STABLE_ID" as "sampleId",          "cancer_study"."CANCER_STUDY_IDENTIFIER" as "geneticProfile.studyId",          "genetic_profile"."STABLE_ID" as "geneticProfileId"          from "mutation"         inner join "mutation_event" on "mutation"."MUTATION_EVENT_ID" = "mutation_event"."MUTATION_EVENT_ID"         inner join "sample" on "mutation"."SAMPLE_ID" = "sample"."INTERNAL_ID"         inner join "gene" on "mutation"."ENTREZ_GENE_ID" = "gene"."ENTREZ_GENE_ID"         inner join "genetic_profile" on "genetic_profile"."GENETIC_PROFILE_ID" = "mutation"."GENETIC_PROFILE_ID"         inner join "cancer_study" on "genetic_profile"."CANCER_STUDY_ID" = "cancer_study"."CANCER_STUDY_ID"                       inner join "sample_list_list" on "sample_list_list"."SAMPLE_ID"="sample"."INTERNAL_ID"             inner join "sample_list" on "sample_list"."LIST_ID"="sample_list_list"."LIST_ID"                    WHERE "genetic_profile"."STABLE_ID" in                 (                     ?                 )                                           and "gene"."HUGO_GENE_SYMBOL" in                 (                     ?                 ,                     ?                 ,                     ?                 )                                                        and "sample_list"."STABLE_ID" = ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."CENTER" as "sequencingCenter",
        "mutation"."MUTATION_STATUS" as "mutati' at line 3
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."CENTER" as "sequencingCenter",
        "mutation"."MUTATION_STATUS" as "mutati' at line 3] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."CENTER" as "sequencingCenter",
        "mutation"."MUTATION_STATUS" as "mutati' at line 3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:90)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	at com.sun.proxy.$Proxy206.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy213.getMutations(Unknown Source)
	at org.cbioportal.persistence.mybatis.MutationMyBatisRepository.getMutations(MutationMyBatisRepository.java:19)
	at org.cbioportal.service.impl.MutationServiceImpl.getMutations(MutationServiceImpl.java:20)
	at org.mskcc.cbio.portal.service.ApiService.getGeneticProfileData(ApiService.java:363)
	at org.mskcc.cbio.portal.service.ApiService$$FastClassBySpringCGLIB$$e4cf2f40.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
	at org.mskcc.cbio.portal.service.ApiService$$EnhancerBySpringCGLIB$$426659a7.getGeneticProfileData(<generated>)
	at org.mskcc.cbio.portal.web.api.ApiController.getGeneticProfileData(ApiController.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:302)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sheridancbio** [comment]
Stewart pointed out an error to me previously that may be causing this. It has to do with configuring the MYSQL database to allow ANSI quotation (which it previously did by default, but now it does not). There is a server configuration setting "sql-mode". See http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes

**Comment by ersinciftci** [comment]
@sheridancbio we don't need to change the default configuration though, my Sprint 2 PR will fix this.

**Comment by jjgao** [comment]
@ersinciftci we should fix this soon in the rc branch. Do you think your Sprint 2 PR can be merged soon? If not, could you separate the code to fix the current rc?

**Comment by ersinciftci** [comment]
Should be merged in 1-2 days, I'll separate it if it doesn't get merged until Friday.

**Comment by ersinciftci** [comment]
@jjgao https://github.com/cBioPortal/cbioportal/pull/1386 is ready to merge and will solve this issue.

**Comment by pieterlukasse** [comment]
FYI - The following view is also failing because of this issue:

![image](https://cloud.githubusercontent.com/assets/2900303/16394046/99312f88-3cb3-11e6-8efd-87c0b77f7635.png)

**Comment by kburkitt** [comment]
@pieterlukasse The fix was merged to rc 10 days ago but I'm not sure if @jjgao deployed it to beta yet.

**Comment by ersinciftci** [comment]
@pieterlukasse The fix was merged to rc 10 days ago but I'm not sure if @jjgao deployed it to beta yet.

**Comment by ecerami** [comment]
@ersinciftci:  is this now totally fixed?   If so, please close.  Thanks.

**Comment by ersinciftci** [comment]
@jjgao is there any error in the logs after the change? Can we close it?
