### ISSUE TITLE
Database Host not picked up from portal.properties

### ISSUE THREAD

**Issue by serverhorror** [cBioPortal/cbioportal#14]
Hello,

It seems that neither the `db.host`, `db.connection_string`.

When I build on a host that is remote to the MySQL database then the build fails with the error below. As soon as I build on a host that has MySQL available on localhost things work.

*`~/.m2/settings.xml`*
```
<settings>
	<proxies>
		<proxy>
		  <id>px</id>
		  <active>true</active>
		  <protocol>http</protocol>
		  <host>px</host>
		  <port>80</port>
		  <username>user</username>
		  <password>pass</password>
		  <nonProxyHosts>*.example.invalid|localhost|bio-mysql|172.20.96.0/22</nonProxyHosts>
		  <!-- this has no effect either
		  <nonProxyHosts>*.example.invalid|localhost|bio-mysql.example.invalid|172.20.96.0/22</nonProxyHosts>		  
		  -->
		</proxy>
	</proxies>
	<servers>
		<server>
			<id>settingsKey</id>
			<username>cbio_user</username>
			<password>supersecure</password>
		</server>
	</servers>
</settings>
```

*portal.properties*

```
# app name
app.name=cbioportal
app.version=1.0

# database
db.user=cbio_user
db.password=supersecure
# FQDN's also don't get picked up
db.host=bio-mysql
db.portal_db_name=cbioportal
db.driver=com.mysql.jdbc.Driver
# FQDN's also don't get picked up
db.connection_string=jdbc:mysql://bio-mysql/
db.tomcat_resource_name=jdbc/cbioportal
# .... cut for brevity...
```

*mvn -DskipTests install*
```
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Portal Master ...................................... SUCCESS [  0.495 s]
[INFO] Portal Business Layer .............................. SUCCESS [ 11.675 s]
[INFO] Portal Core ........................................ FAILURE [  4.647 s]
[INFO] Portal Web Layer ................................... SKIPPED
[INFO] cBio Cancer Genomics Portal ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.070 s
[INFO] Finished at: 2015-05-11T14:06:40+02:00
[INFO] Final Memory: 52M/1860M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:sql-maven-plugin:1.5:execute (default) on project core: Communications link failure due to underlying exception:
[ERROR]
[ERROR] ** BEGIN NESTED EXCEPTION **
[ERROR]
[ERROR] java.net.SocketException
[ERROR] MESSAGE: java.net.ConnectException: Connection refused
[ERROR]
[ERROR] STACKTRACE:
[ERROR]
[ERROR] java.net.SocketException: java.net.ConnectException: Connection refused
[ERROR] at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:156)
[ERROR] at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:276)
[ERROR] at com.mysql.jdbc.Connection.createNewIO(Connection.java:2641)
[ERROR] at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
[ERROR] at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
[ERROR] at org.codehaus.mojo.sql.SqlExecMojo.getConnection(SqlExecMojo.java:899)
[ERROR] at org.codehaus.mojo.sql.SqlExecMojo.execute(SqlExecMojo.java:612)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]
[ERROR] ** END NESTED EXCEPTION **
[ERROR]
[ERROR]
[ERROR]
[ERROR] Last packet sent to the server was 9 ms ago.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core
```

**Comment by serverhorror** [comment]
It seems that around (Line 226)[https://github.com/cBioPortal/cbioportal/commit/e80fac1c5fd7e713b341a341aed405a69a9a048a#diff-357e4854869b2e21c38b1b437f11095aR226] the `settingsKey` shouldn't actually contain a hardcoded URI to MySQL

**Comment by tjrivera** [comment]
I've also run into this issue. Should the build process use the database defined here: https://github.com/cBioPortal/cbioportal/blob/master/src/main/resources/portal.properties.EXAMPLE#L7 to run its tests during build?

**Comment by serverhorror** [comment]
I think the the maven settings is definitely the wrong place to look for cBioportal settings. Im in favor of the portal.properties.

**Comment by jjgao** [comment]
@serverhorror @tjrivera Have you solved the problem? Database should be configured in Tomcat context.xml file.

https://github.com/cBioPortal/cbioportal/wiki/Pre-Build-Steps#configure-the-database-connection-pool-resource-to-apache-tomcat

**Comment by tjrivera** [comment]
@jjgao I think this refers specifically to the build process and the fact that the MySQL db that is used to test against during the build is hardcoded here. 

https://github.com/cBioPortal/cbioportal/commit/e80fac1c5fd7e713b341a341aed405a69a9a048a#diff-357e4854869b2e21c38b1b437f11095aR226
(Line 226)

This makes it impossible to build cBio on a machine that doesn't have a MySQL instance running on localhost. I've worked around this by building the application with Docker containers but perhaps the test db should also be configurable?

**Comment by inodb** [comment]
I fixed the problem of not being able to build the war without mysql in https://github.com/cBioPortal/cbioportal/pull/605 when the parameter `-DskipTests` is supplied to `mvn`. You still can't set the test db in the properties file however.

**Comment by serverhorror** [comment]
How's it going with this? Any fix yet?
