### ISSUE TITLE
jsoptsimple OptionException in ImportCancerStudy

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#1626]
When running:

```
java  -cp /Library/Tomcat//lib/mysql-connector-java-5.1.35-bin.jar:/Users/debruiji/git/cbioportal-mini/core/target/core-1.3.0-SNAPSHOT.jar org.mskcc.cbio.portal.scripts.ImportCancerStudy meta_study.txt
```

on rc 58f74eb48a94c5b33a7029ecf9421ef72e354c37

```
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionException
        at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:158)
        at org.mskcc.cbio.portal.scripts.ImportCancerStudy.main(ImportCancerStudy.java:88)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
make: *** [import] Error 1
```

**Comment by jjgao** [comment]
@inodb I am closing this. Please reopen if the issue still stands.
