### ISSUE TITLE
Cannot import studies

### ISSUE THREAD

**Issue by dullahan8** [cBioPortal/cbioportal#2509]
I'm working through installing cBioportal and everything is going smoothly up until I attempt to import the sample study in the setup guide here [https://cbioportal.readthedocs.io/en/latest/Load-Sample-Cancer-Study.html](https://cbioportal.readthedocs.io/en/latest/Load-Sample-Cancer-Study.html).

I'm currently on the master branch and the error I get is: 
```
$ ./validateData.py -s ../../../test/scripts/test_data/study_es_0/ -n
Traceback (most recent call last):
  File "./validateData.py", line 3211, in <module>
    exit_status = main_validate(parsed_args)
  File "./validateData.py", line 3092, in main_validate
    exit_status_handler = MaxLevelTrackingHandler()
  File "./validateData.py", line 87, in __init__
    super(MaxLevelTrackingHandler, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```
```
$ ./metaImport.py -s ../../../test/scripts/test_data/study_es_0/ -n
Starting validation...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during validation step:
Traceback (most recent call last):
  File "./metaImport.py", line 91, in <module>
    exitcode = validateData.main_validate(args)
  File "/opt/cbioportal/core/src/main/scripts/importer/validateData.py", line 3075, in main_validate
    exit_status_handler = MaxLevelTrackingHandler()
  File "/opt/cbioportal/core/src/main/scripts/importer/validateData.py", line 86, in __init__
    super(MaxLevelTrackingHandler, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```

**Comment by wuwu1995** [comment]
I'll just change it to python2.7.I suggest you have a try.

**Comment by dullahan8** [comment]
I pulled from the master branch this morning and tried again. Is this normal?
`$ python -V
Python 2.7.11
$ ./validateData.py -s ../../../test/scripts/test_data/study_es_0/ -n
Traceback (most recent call last):
  File "./validateData.py", line 40, in <module>
    import requests
ImportError: No module named requests
`

**Comment by dullahan8** [comment]
Sorry, I just realized that it is my python that is missing a module and not the validator's fault. I installed the module and the output is now this:
```
INFO: -: Running validation from cBioPortal version 1.7.1
WARNING: -: Skipping validations relating to cancer types defined in the portal
WARNING: -: Skipping validations relating to gene identifiers and aliases defined in the portal
WARNING: -: Skipping validations relating to gene set identifiers

INFO: meta_expression_median.txt: Validation of meta file complete

INFO: meta_gsva_scores.txt: Validation of meta file complete

INFO: meta_mutations_extended.txt: Validation of meta file complete

INFO: meta_CNA.txt: Validation of meta file complete

INFO: brca_tcga_meta_cna_hg19_seg.txt: Validation of meta file complete

INFO: meta_expression_median_Zscores.txt: Validation of meta file complete

INFO: meta_fusion.txt: Validation of meta file complete

INFO: meta_patients.txt: Validation of meta file complete

INFO: meta_gsva_pvalues.txt: Validation of meta file complete

INFO: meta_log2CNA.txt: Validation of meta file complete

INFO: meta_methylation_hm27.txt: Validation of meta file complete

INFO: meta_gistic_genes_amp.txt: Validation of meta file complete

INFO: meta_gene_panel_matrix.txt: Validation of meta file complete

INFO: meta_study.txt: Validation of meta file complete

INFO: meta_samples.txt: Validation of meta file complete

INFO: meta_cancer_type.txt: Validation of meta file complete

INFO: cancer_type.txt: Validation of file complete
INFO: cancer_type.txt: Read 1 lines. Lines with warning: 0. Lines with error: 0

INFO: data_samples.txt: Validation of file complete
INFO: data_samples.txt: Read 831 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gene_panel_matrix.txt: Validation of file complete
INFO: data_gene_panel_matrix.txt: Read 2 lines. Lines with warning: 0. Lines with error: 0

INFO: brca_tcga_data_cna_hg19.seg: Validation of file complete
INFO: brca_tcga_data_cna_hg19.seg: Read 10 lines. Lines with warning: 0. Lines with error: 0

INFO: data_methylation_hm27.txt: Validation of file complete
INFO: data_methylation_hm27.txt: Read 9 lines. Lines with warning: 0. Lines with error: 0

INFO: data_fusions.txt: Validation of file complete
INFO: data_fusions.txt: Read 4 lines. Lines with warning: 0. Lines with error: 0

INFO: data_expression_median.txt: Validation of file complete
INFO: data_expression_median.txt: Read 7 lines. Lines with warning: 0. Lines with error: 0

INFO: data_expression_median_Zscores.txt: Validation of file complete
INFO: data_expression_median_Zscores.txt: Read 6 lines. Lines with warning: 0. Lines with error: 0

INFO: brca_tcga_pub.maf: lines [7, 9, 14]: Validation of line skipped due to cBioPortal's filtering. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; value encountered: 'Silent'
INFO: brca_tcga_pub.maf: Validation of file complete
INFO: brca_tcga_pub.maf: Read 15 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gsva_pvalues.txt: Validation of file complete
INFO: data_gsva_pvalues.txt: Read 10 lines. Lines with warning: 0. Lines with error: 0

INFO: data_CNA.txt: Validation of file complete
INFO: data_CNA.txt: Read 8 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gsva_scores.txt: Validation of file complete
INFO: data_gsva_scores.txt: Read 10 lines. Lines with warning: 0. Lines with error: 0

INFO: data_patients.txt: Validation of file complete
INFO: data_patients.txt: Read 830 lines. Lines with warning: 0. Lines with error: 0

INFO: data_log2CNA.txt: Validation of file complete
INFO: data_log2CNA.txt: Read 8 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gistic_genes_amp.txt: Validation of file complete
INFO: data_gistic_genes_amp.txt: Read 15 lines. Lines with warning: 0. Lines with error: 0

INFO: case_lists/cases_custom.txt: Validation of meta file complete

INFO: -: Validation of case list folder complete
INFO: -: Validation complete
Validation of study succeeded with warnings.
```

**Comment by dullahan8** [comment]
Running ./metaImport.py now and ran into a new error:
```
#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Expected to find 1 scripts-*.jar, but found: 0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
```
