### ISSUE TITLE
Cross Cancer Query Page parameters needs rewrite rule to hash parameters

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2663]
https://sentry.io/memorial-sloan-kettering/cbioportal-frontend/issues/301581055/

```
Error: cannot GET http://www.cbioportal.org/api/studies/all/significantly-mutated-genes (404)
  at l.toError (/reactapp/main.app.js:12:19117)
  at l.r._setStatusProperties (/reactapp/main.app.js:12:30022)
  at new l (/reactapp/main.app.js:12:16329)
  at c.<anonymous> (/reactapp/main.app.js:12:16840)
  at c.r.emit (/reactapp/main.app.js:12:24519)
...
(2 additional frame(s) were not displayed)
```

**Comment by inodb** [comment]
I think we'll need a URL rewrite for old style cross cancer query parameters to new style, since it seems most of these errors come from Google originally.

**Comment by jjgao** [comment]
ice boxed it until virtual study feature is merged.
