### ISSUE TITLE
an error when importing study_es_0

### ISSUE THREAD

**Issue by eastar2016** [cBioPortal/cbioportal#2735]
I installed the cbioportal_1.7.2 on my server as the manual describes. but when i imported the study_es_0, there was an error as follows.
-----------------------------------------------------------------------------------------------------------
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.run(ImportTypesOfCancers.java:66)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.main(ImportTypesOfCancers.java:122)
Caused by: org.mskcc.cbio.portal.dao.DaoException: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
at org.mskcc.cbio.portal.dao.DaoTypeOfCancer.getTypeOfCancerById(DaoTypeOfCancer.java:88)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.load(ImportTypesOfCancers.java:87)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.run(ImportTypesOfCancers.java:62)
... 2 more
Caused by: java.sql.SQLException: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:120)
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:102)
at org.mskcc.cbio.portal.dao.DaoTypeOfCancer.getTypeOfCancerById(DaoTypeOfCancer.java:79)
... 4 more
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:117)
... 6 more
Caused by: java.sql.SQLException: Access denied for user 'cbio_user'@'localhost' (using password: YES)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
... 9 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "./metaImport.py", line 119, in <module>
    cbioportalImporter.main(args)
  File "/public/home/yudong/Software/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 334, in main
    process_directory(jvm_args, study_directory)
  File "/public/home/yudong/Software/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 212, in process_directory
    import_cancer_type(jvm_args, data_filename)
  File "/public/home/yudong/Software/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 54, in import_cancer_type
    run_java(*args)
  File "/public/home/yudong/Software/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 784, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.
-----------------------------------------------------------------------------------------------------------------
 
how could i solve this problem? 
Can someone give advices?

the mysql database cbioportal can be logged normally.

**Comment by ecerami** [comment]
This looks like a database user permission issue.  Have you followed the steps on:  "Creating the cBioPortal MySQL Databases and User" at:  https://cbioportal.readthedocs.io/en/latest/Pre-Build-Steps.html
