### ISSUE TITLE
Blocking issue when using SAML authentication

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3166]
I am getting this in tomcat logs when trying to run the branch from PR #2525
```
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
java.lang.NoSuchMethodError: org.apache.xml.serializer.Encodings.isRecognizedEncoding(Ljava/lang/String;)Z
	at org.apache.xml.serializer.dom3.LSSerializerImpl.write(LSSerializerImpl.java:926)
	at org.opensaml.xml.util.XMLHelper.writeNode(XMLHelper.java:892)
	at org.opensaml.xml.util.XMLHelper.writeNode(XMLHelper.java:872)
	at org.opensaml.xml.util.XMLHelper.nodeToString(XMLHelper.java:834)
	at org.opensaml.xml.XMLConfigurator.load(XMLConfigurator.java:159)
	at org.opensaml.xml.XMLConfigurator.load(XMLConfigurator.java:143)
	at org.opensaml.DefaultBootstrap.initializeXMLTooling(DefaultBootstrap.java:203)
	at org.opensaml.DefaultBootstrap.initializeXMLTooling(DefaultBootstrap.java:186)
	at org.opensaml.DefaultBootstrap.bootstrap(DefaultBootstrap.java:92)
	at org.opensaml.PaosBootstrap.bootstrap(PaosBootstrap.java:27)
	at org.springframework.security.saml.SAMLBootstrap.postProcessBeanFactory(SAMLBootstrap.java:42)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:177)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:609)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pieterlukasse** [comment]
Will probably only affect instances running on tomcat 8. Tomcat 7 seems to work.

**Comment by pieterlukasse** [comment]
Troubleshooting: release 1.8.2...same problem. But with 1.6.1 I do not get this error. Issue traced back to this commit: https://github.com/cBioPortal/cbioportal/commit/f754c9a

**Comment by pieterlukasse** [comment]
I pushed a solution here: https://github.com/thehyve/cbioportal/commit/8cf1f387914af1b2dcce833d81a0c075ca57758f  (:warning: tested for SAML only)

**Comment by pieterlukasse** [comment]
extra fix: @ersinciftci has also found an extra fix that needs to be done in `/security/security-spring/pom.xml`:
```
<build>
    <filters>
        <filter>../../src/main/resources/portal.properties</filter>
    </filters>
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>
</build>
```

**Comment by pieterlukasse** [comment]
Given it also occurs in `master` (at least tested with 1.8.2), labeling as "critical".

**Comment by messersc** [comment]
Hi Pieter,

I remember seeing something like `java.lang.NoSuchMethodError: org.apache.xml.serializer.Encodings.isRecognizedEncoding(Ljava/lang/String;)Z` in the logs when running the code from the PR, but I thought it was something that had to do with our setup (docker on flynn).

The funny thing was that this error was not reproducible, so roughly every second deploy worked. I can try do dig out the logs later.

**Comment by pieterlukasse** [comment]
@messersc thanks for sharing this. I just tried again now on `hotfix` vs my fix on top of `hotfix` and I was able to reproduce the problems (and the solution :smile:  ). So I will go ahead with a PR for now. Not sure what caused the issue to automagically disappear on your side.

**Comment by messersc** [comment]
I have not seen this error since upgrading, so this can probably be closed. Thanks Pieter!
