### ISSUE TITLE
MySQL migration fails for 2.6.0

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#3929]
Hi,

the sql script file is missing a colon, so the migration crashes with

```
./migrate_db.py -p ../../../../src/main/resources/portal.properties -s ../../../../db-scripts/src/main/resources/migration.sql 
WARNING: This script will alter your database! Be sure to back up your data before running.
Continue running DB migration? (y/n) y
Traceback (most recent call last):
  File "./migrate_db.py", line 263, in <module>
    main()
  File "./migrate_db.py", line 256, in main
    run_migration(db_version, sql_filename, connection, cursor)
  File "./migrate_db.py", line 161, in run_migration
    sql_version = tuple(map(int, line.split(':')[1].strip().split('.')))
IndexError: list index out of range
```

Fix:

```diff
diff --git a/db-scripts/src/main/resources/migration.sql b/db-scripts/src/main/resources/migration.sql
index 96c7483..6e668df 100644
--- a/db-scripts/src/main/resources/migration.sql
+++ b/db-scripts/src/main/resources/migration.sql
@@ -446,9 +446,9 @@ c1.`CANCER_STUDY_ID` = cancer_study.`CANCER_STUDY_ID` GROUP BY cancer_study.`CAN
 
 UPDATE info SET DB_SCHEMA_VERSION="2.5.0";
 
-##version 2.6.0
+##version: 2.6.0
 -- modify fkc for gistic_to_gene
 ALTER TABLE gistic_to_gene DROP FOREIGN KEY gistic_to_gene_ibfk_2;
 ALTER TABLE gistic_to_gene ADD CONSTRAINT `gistic_to_gene_ibfk_2` FOREIGN KEY (`GISTIC_ROI_ID`) REFERENCES `gistic` (`GISTIC_ROI_ID`) ON DELETE CASCADE;
 
-UPDATE info SET DB_SCHEMA_VERSION="2.6.0";
\ No newline at end of file
+UPDATE info SET DB_SCHEMA_VERSION="2.6.0";
```

Should I do a PR or is a less hassle for a member of the team?

Kind regards,
Clemens

**Comment by jjgao** [comment]
@messersc thank you for bring this into our attention. Please send us a pr -- we would love to have community contributions :)

**Comment by messersc** [comment]
@jjgao Happy to to do this. See referenced PR.

Cheers,
Clemens

**Comment by jjgao** [comment]
@messersc thank you for the help and congratulations to your first pr to the cbioportal :)
