### ISSUE TITLE
No bean named 'springSecurityFilterChain' is defined

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#461]
Hi, I'm trying to get a new install of cbioportal working with SAML and so far I can't even start it. I am getting the following error:

    SEVERE: Exception starting filter springSecurityFilterChain
    org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'springSecurityFilterChain' is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:641)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1159)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:282)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:979)
    at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:324)
    at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235)
    at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4809)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5485)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    Nov 13, 2015 4:28:59 PM org.apache.catalina.core.StandardContext startInternal
    SEVERE: Error filterStart

this is my portal.properties for authentication

    # authentication
    ## is authentication enabled at all? (true, false)
    authenticate=true
    ## which method of authentication to use (false, googleplus, saml, openid)
    authorization=saml
    ## Should the permissions for groups and users be filtered by this instance's app.name?
    ## (true means the system only handles "CBIOPORTAL:someGroupPermission" groups, false means "someGroupPermission" works)
    filter_groups_by_appname=true
    ## settings to connect to googleplus auth infrastructure
    googleplus.consumer.key=
    googleplus.consumer.secret=
    ## settings to connect to SAML auth server
    saml.sp.metadata.entityid=cbioportal
    saml.idp.metadata.location=classpath:/metadata.xml
    saml.idp.metadata.entityid=cbioportal
    saml.keystore.location=classpath:/samlKeystore.jks
    saml.keystore.password=***
    saml.keystore.private-key.key=secure-key
    saml.keystore.private-key.password=***
    saml.keystore.default-key=secure-key
    ## settings to connect to an Active Directory domain controller
    ad.domain=
    ad.url=
    # always show studies with this group
    always_show_study_group=

I've followed the steps on the wiki page, I've put my keystore and metadata files into WEB-INF/classes so that they are on classpath and accessible and readable by tomcat.
I've searched the internet and found pointers to /var/lib/tomcat/webapps/cbioportal/WEB-INF/web.xml so here are the relevant bits

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>classpath:applicationContext-security.xml classpath:applicationContext-business.xml</param-value>
    </context-param>
    ...
    
    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
    ...

    <filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>

    <filter-mapping>
      <filter-name>springSecurityFilterChain</filter-name>
      <url-pattern>/*</url-pattern>
    </filter-mapping>

applicationContext-security.xml is in WEB-INF/classes and readable by tomcat and seems to contain <beans> with <http> configuration in it. 
I'm on CentOS Linux release 7.1.1503 .

What can I do to fix this?

**Comment by j-hudecek** [comment]
just a note: when I set authentication and authorization to false it works

**Comment by zheins** [comment]
Try this in your properties file:

authenticate=saml 
authorization=true 

I got the same error when I switched them and deployed.

**Comment by j-hudecek** [comment]
Yes that was it. Thanks!
