### ISSUE TITLE
Issues importing study_es_0

### ISSUE THREAD

**Issue by cmonnom** [cBioPortal/cbioportal#4743]
I can't pass the **Import Gene Panel for Sample Study** step:
`importGenePanel.pl --data ../../test/scripts/test_data/study_es_0/gene_panel_example.txt`
`Reading data from:  /opt/cbioportal/core/src/main/scripts/../../test/scripts/test_data/study_es_0/gene_panel_example.txt`

`ABORTED!
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
 Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
 The error may exist in org/mskcc/cbio/portal/persistence/GenePanelMapperLegacy.xml
 The error may involve org.mskcc.cbio.portal.persistence.GenePanelMapperLegacy.getGeneByHugoSymbol
 The error occurred while executing a query
 Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:79)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
        at com.sun.proxy.$Proxy12.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:167)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
        at com.sun.proxy.$Proxy14.getGeneByHugoSymbol(Unknown Source)
        at org.mskcc.cbio.portal.repository.GenePanelMyBatisRepositoryLegacy.getGeneByHugoSymbol(GenePanelMyBatisRepositoryLegacy.java:83)
        at org.mskcc.cbio.portal.scripts.ImportGenePanel.getGenes(ImportGenePanel.java:167)
        at org.mskcc.cbio.portal.scripts.ImportGenePanel.importData(ImportGenePanel.java:99)
        at org.mskcc.cbio.portal.scripts.ImportGenePanel.run(ImportGenePanel.java:82)
        at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
        at org.mskcc.cbio.portal.scripts.ImportGenePanel.main(ImportGenePanel.java:202)
Caused by: org.apache.ibatis.exceptions.PersistenceException:
Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
 The error may exist in org/mskcc/cbio/portal/persistence/GenePanelMapperLegacy.xml
 The error may involve org.mskcc.cbio.portal.persistence.GenePanelMapperLegacy.getGeneByHugoSymbol
 The error occurred while executing a query
 Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
        ... 11 more
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:84)
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:70)
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:103)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
        ... 18 more
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'cbio_user'@'localhost' (using password: YES))
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
        ... 28 more
Caused by: java.sql.SQLException: Access denied for user 'cbio_user'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
        at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
        at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
        at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
        ... 32 more`

It looks like the error is in connecting to the database.
I've followed all the steps up to that point and I'm using MySQL 5.7.
I have a ~/.m2/settings.xml file with the cbio_user credentials (I only changed the password from this example file):
`<settings>
  <servers>
    <server>
      <id>settingsKey</id>
      <username>cbio_user</username>
      <password>somepassword</password>
    </server>
  </servers>
</settings>`

I've successfully run the **Import the cBioPortal Seed Database** step using the same credentials that are in the settings.xml file.

The only thing I noticed is that the mvn build did have a bunch of warnings (I've removed most the INFO lines to keep it short:
`[WARNING] The POM for org.biojava.thirdparty:forester:jar:1.038 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`

`[WARNING] apache-log4j-extras-1.1.jar, log4j-1.2.16.jar define 158 overlappping classes:
[WARNING]   - org.apache.log4j.pattern.MessagePatternConverter
[WARNING]   - org.apache.log4j.xml.DOMConfigurator$4
[WARNING]   - org.apache.log4j.varia.StringMatchFilter
[WARNING]   - org.apache.log4j.spi.OptionHandler
[WARNING]   - org.apache.log4j.pattern.NameAbbreviator$DropElementAbbreviator
[WARNING]   - org.apache.log4j.pattern.LevelPatternConverter
[WARNING]   - org.apache.log4j.helpers.BoundedFIFO
[WARNING]   - org.apache.log4j.pattern.BridgePatternParser
[WARNING]   - org.apache.log4j.BasicConfigurator
[WARNING]   - org.apache.log4j.pattern.LoggingEventPatternConverter
[WARNING]   - 148 more...
[WARNING] xml-apis-1.3.04.jar, axis-jaxrpc-1.4.jar define 1 overlappping classes:
[WARNING]   - javax.xml.namespace.QName
[WARNING] serializer-2.7.1.jar, xalan-2.6.0.jar define 48 overlappping classes:
[WARNING]   - org.apache.xml.serializer.ObjectFactory$ConfigurationError
[WARNING]   - org.apache.xml.serializer.XSLOutputAttributes
[WARNING]   - org.apache.xml.serializer.OutputPropertiesFactory
[WARNING]   - org.apache.xml.serializer.Serializer
[WARNING]   - org.apache.xml.serializer.ToXMLSAXHandler
[WARNING]   - org.apache.xml.serializer.Encodings
[WARNING]   - org.apache.xml.serializer.SecuritySupport12$5
[WARNING]   - org.apache.xml.serializer.ObjectFactory
[WARNING]   - org.apache.xml.serializer.DOMSerializer
[WARNING]   - org.apache.xml.serializer.SecuritySupport12$3
[WARNING]   - 38 more...
[WARNING] xml-apis-1.3.04.jar, batik-ext-1.7.jar define 8 overlappping classes:
[WARNING]   - org.w3c.dom.events.MouseEvent
[WARNING]   - org.w3c.dom.events.MutationEvent
[WARNING]   - org.w3c.dom.events.Event
[WARNING]   - org.w3c.dom.events.EventListener
[WARNING]   - org.w3c.dom.events.DocumentEvent
[WARNING]   - org.w3c.dom.events.EventException
[WARNING]   - org.w3c.dom.events.EventTarget
[WARNING]   - org.w3c.dom.events.UIEvent
[WARNING] xml-apis-1.3.04.jar, jaxen-1.1.6.jar define 1 overlappping classes:
[WARNING]   - org.w3c.dom.UserDataHandler
[WARNING] javax.inject-1.jar, javax.inject-2.5.0-b05.jar define 6 overlappping classes:
[WARNING]   - javax.inject.Inject
[WARNING]   - javax.inject.Singleton
[WARNING]   - javax.inject.Scope
[WARNING]   - javax.inject.Named
[WARNING]   - javax.inject.Provider
[WARNING]   - javax.inject.Qualifier
[WARNING] aopalliance-repackaged-2.5.0-b05.jar, aopalliance-1.0.jar, spring-aop-4.3.14.RELEASE.jar define 9 overlappping classes:
[WARNING]   - org.aopalliance.intercept.ConstructorInterceptor
[WARNING]   - org.aopalliance.intercept.MethodInvocation
[WARNING]   - org.aopalliance.intercept.MethodInterceptor
[WARNING]   - org.aopalliance.intercept.Invocation
[WARNING]   - org.aopalliance.aop.AspectException
[WARNING]   - org.aopalliance.intercept.Interceptor
[WARNING]   - org.aopalliance.intercept.Joinpoint
[WARNING]   - org.aopalliance.aop.Advice
[WARNING]   - org.aopalliance.intercept.ConstructorInvocation
[WARNING] xml-apis-1.3.04.jar, xalan-2.6.0.jar define 6 overlappping classes:
[WARNING]   - org.w3c.dom.xpath.XPathExpression
[WARNING]   - org.w3c.dom.xpath.XPathEvaluator
[WARNING]   - org.w3c.dom.xpath.XPathNSResolver
[WARNING]   - org.w3c.dom.xpath.XPathException
[WARNING]   - org.w3c.dom.xpath.XPathNamespace
[WARNING]   - org.w3c.dom.xpath.XPathResult
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
[INFO] Reactor Summary:
[INFO]
[INFO] Portal Master 1.16.1-SNAPSHOT ...................... SUCCESS [  1.150 s]
[INFO] model .............................................. SUCCESS [  1.161 s]
[INFO] Portal Business Layer .............................. SUCCESS [  0.516 s]
[INFO] persistence ........................................ SUCCESS [  0.016 s]
[INFO] persistence-api .................................... SUCCESS [  0.104 s]
[INFO] db-scripts ......................................... SUCCESS [  0.103 s]
[INFO] persistence-mybatis ................................ SUCCESS [  0.810 s]
[INFO] service ............................................ SUCCESS [  1.242 s]
[INFO] Portal Web Layer ................................... SUCCESS [  1.910 s]
[INFO] security ........................................... SUCCESS [  0.016 s]
[INFO] security-spring .................................... SUCCESS [  0.316 s]
[INFO] Portal Core ........................................ SUCCESS [  3.989 s]
[INFO] cBioPortal ......................................... SUCCESS [  6.981 s]
[INFO] Portal Scripts 1.16.1-SNAPSHOT ..................... SUCCESS [  8.683 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.310 s
[INFO] Finished at: 2018-08-31T16:39:20-04:00
[INFO] ------------------------------------------------------------------------`

**Comment by cmonnom** [comment]
So, I solved my own issue. The password was wrong.

Just for the poor souls stuck at this step, this is because you are REQUIRED to create a mysql user "cbio_user" and a password "somepassword". Don't use your own username or password. You might need to change the MySQL password requirements to allow weak passwords.

Not sure why it's hard coded when we create a settings.xml file but I guess cbioportal is not using it at this point.

Anyway, follow instructions to the letter (including how to spell passwords)

**Comment by lakhujanivijay** [comment]
When you say " Don't use your own username or password", do you mean I should use username "cbio_user" and password "somepassword" ? Like this?

```
mysql> CREATE USER 'cbio_user'@'localhost' IDENTIFIED BY 'somepassword';
    Query OK, 0 rows affected (0.00 sec)

```
and then  

# open the settings file
gedit ~/.m2/settings.xml

# and edit the file with the username and password like this

```
    <server>
      <id>deploymentRepo</id>
      <username>cbio_user</username>
      <password>somepassword</password>
    </server>

```
