### ISSUE TITLE
Error encountered while executing validateData.py

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#5918]
Hi,

I am trying to run the following command but I am encountering an issue with this:

```
./validateData.py -s /home/bioinfo/cbioportal/core/src/test/scripts/test_data/study_es_0 -n

```

and the output is

```
./validateData.py:3770: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parsedYaml = yaml.load(stream)
INFO: -: Running validation from cBioPortal version 0-unknown-version-SNAPSHOT
WARNING: -: Skipping validations relating to cancer types defined in the portal
WARNING: -: Skipping validations relating to gene identifiers and aliases defined in the portal
WARNING: -: Skipping validations relating to gene set identifiers
WARNING: -: Skipping validations relating to gene panel identifiers

INFO: meta_cancer_type.txt: Validation of meta file complete

INFO: meta_clinical_patients.txt: Validation of meta file complete

INFO: meta_clinical_samples.txt: Validation of meta file complete

INFO: meta_cna_discrete.txt: Validation of meta file complete

INFO: meta_cna_hg19_seg.txt: Validation of meta file complete

INFO: meta_cna_log2.txt: Validation of meta file complete

INFO: meta_expression_median.txt: Validation of meta file complete

INFO: meta_expression_median_Zscores.txt: Validation of meta file complete

INFO: meta_fusions.txt: Validation of meta file complete

INFO: meta_gene_panel_matrix.txt: Validation of meta file complete

INFO: meta_gistic_genes_amp.txt: Validation of meta file complete

INFO: meta_gsva_pvalues.txt: Validation of meta file complete

INFO: meta_gsva_scores.txt: Validation of meta file complete

INFO: meta_methylation_hm27.txt: Validation of meta file complete

INFO: meta_mutations_extended.txt: Validation of meta file complete

INFO: meta_study.txt: Validation of meta file complete

INFO: data_cancer_type.txt: Validation of file complete
INFO: data_cancer_type.txt: Read 1 lines. Lines with warning: 0. Lines with error: 0

INFO: data_clinical_samples.txt: Validation of file complete
INFO: data_clinical_samples.txt: Read 846 lines. Lines with warning: 0. Lines with error: 0

INFO: study_tags.yml: Validation of study tags file complete.

INFO: data_cna_discrete.txt: Validation of file complete
INFO: data_cna_discrete.txt: Read 9 lines. Lines with warning: 0. Lines with error: 0

INFO: data_clinical_patients.txt: Validation of file complete
INFO: data_clinical_patients.txt: Read 845 lines. Lines with warning: 0. Lines with error: 0

INFO: data_expression_median.txt: Validation of file complete
INFO: data_expression_median.txt: Read 7 lines. Lines with warning: 0. Lines with error: 0

INFO: data_expression_median_Zscores.txt: Validation of file complete
INFO: data_expression_median_Zscores.txt: Read 6 lines. Lines with warning: 0. Lines with error: 0

INFO: data_fusions.txt: Validation of file complete
INFO: data_fusions.txt: Read 6 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gistic_genes_amp.txt: Validation of file complete
INFO: data_gistic_genes_amp.txt: Read 15 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gsva_pvalues.txt: Validation of file complete
INFO: data_gsva_pvalues.txt: Read 8 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gsva_scores.txt: Validation of file complete
INFO: data_gsva_scores.txt: Read 8 lines. Lines with warning: 0. Lines with error: 0

INFO: data_cna_log2.txt: Validation of file complete
INFO: data_cna_log2.txt: Read 8 lines. Lines with warning: 0. Lines with error: 0

INFO: data_methylation_hm27.txt: Validation of file complete
INFO: data_methylation_hm27.txt: Read 9 lines. Lines with warning: 0. Lines with error: 0

INFO: data_mutations_extended.maf: lines [4, 5, 6, (5 more)]: column 164: Values contained in the column cbp_driver_tiers that will appear in the "Mutation Color" menu of the Oncoprint; values encountered: ['Class 2', 'Class 1', 'Class 4', '(1 more)']
INFO: data_mutations_extended.maf: lines [7, 9, 14]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; value encountered: 'Silent'
INFO: data_mutations_extended.maf: Validation of file complete
INFO: data_mutations_extended.maf: Read 38 lines. Lines with warning: 0. Lines with error: 0

INFO: data_cna_hg19.seg: Validation of file complete
INFO: data_cna_hg19.seg: Read 10 lines. Lines with warning: 0. Lines with error: 0

INFO: case_lists/cases_sequenced.txt: Validation of meta file complete

INFO: case_lists/cases_custom.txt: Validation of meta file complete

INFO: case_lists/cases_cnaseq.txt: Validation of meta file complete

INFO: case_lists/cases_cna.txt: Validation of meta file complete

INFO: case_lists/cases_test.txt: Validation of meta file complete

INFO: -: Validation of case list folder complete

INFO: data_gene_panel_matrix.txt: line 1: This column can be replaced by a 'gene_panel' property in the respective meta file; value encountered: 'gistic'
Traceback (most recent call last):
  File "./validateData.py", line 4352, in <module>
    exit_status = main_validate(parsed_args)
  File "./validateData.py", line 4335, in main_validate
    validate_study(study_dir, portal_instance, logger, relaxed_mode, strict_maf_checks)
  File "./validateData.py", line 4210, in validate_study
    validators_by_meta_type[cbioportal_common.MetaFileTypes.GENE_PANEL_MATRIX][0].validate()
  File "./validateData.py", line 366, in validate
    self._validate_file()
  File "./validateData.py", line 479, in _validate_file
    self.checkLine(fields)
  File "./validateData.py", line 2811, in checkLine
    if gene_panel_id not in self.portal.gene_panel_list and gene_panel_id != 'NA':
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by lakhujanivijay** [comment]
I think I got one clue here:


when I run the following command, I could see it's a connection issue. Can you please help ?

```
bioinfo@bioinfo-pc:~/cbioportal/core/src/main/scripts/importer$ ./validateData.py -s ../../../test/scripts/test_data/study_es_0/ -v
INFO: -: Running validation from cBioPortal version 0-unknown-version-SNAPSHOT
DEBUG: -: Requesting cancertypes from portal at 'http://localhost:8080/cbioportal'
Traceback (most recent call last):
  File "./validateData.py", line 3877, in request_from_portal_api
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: http://localhost:8080/cbioportal/api-legacy/cancertypes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./validateData.py", line 4352, in <module>
    exit_status = main_validate(parsed_args)
  File "./validateData.py", line 4330, in main_validate
    portal_instance = load_portal_info(server_url, logger)
  File "./validateData.py", line 3994, in load_portal_info
    parsed_json = request_from_portal_api(path, api_name, logger)
  File "./validateData.py", line 3881, in request_from_portal_api
    ) from e
ConnectionError: Failed to fetch metadata from the portal at [http://localhost:8080/cbioportal/api-legacy/cancertypes]

```

**Comment by timchu90** [comment]
I had the same issue. 
It seems the -n (no portal mode) command isn't working at the moment.
I was able to get the validation running without it, same as your second command. 
Note that the second command requires that you have a running instance of the portal which you should if you followed the previous directions. 
If you have it running at another address, you can use the -u flag to specify that.
See here: https://docs.cbioportal.org/5.1-data-loading/data-loading/using-the-dataset-validator#running-the-validator

**Comment by pieterlukasse** [comment]
@lakhujanivijay , @timchu90 , thanks for reporting the issue. 
Can you please help with some extra details:
- what is the release version you are using?
- can you please try to open the URL http://localhost:8080/cbioportal/api-legacy/cancertypes in a browser (or curl it) on the same machine you are executing the .py script? Please let me know the results.

**Comment by pieterlukasse** [comment]
@lakhujanivijay I see you are trying the docker approach now (https://github.com/thehyve/cbioportal-docker/issues/49)

**Comment by timchu90** [comment]
The issue I had was in regards to lakhujanivijay's first comment. I was following the tutorial's steps.
I am updated with the master branch.

localhost:8080/cbioportal/api-legacy/cancertypes works fine for me and validation using the portal works.
It is specifically validation using the '-n' flag that is not working for me.

I noticed in the cbioportal/datahub tests that certain studies are also failing with the same error:
https://circleci.com/gh/cBioPortal/datahub/1621

I suspect it has to do with the way gene panels are checked.

**Comment by jjgao** [comment]
please email cbioportal@googlegroups.com if you have more questions.
