### ISSUE TITLE
java.io.FileNotFoundException: /logs/public-portal.log (No such file or directory): while executing importGenePanel.pl

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#5919]
Hi 

I am encountering this error while executing `importGenePanel.pl`.

command

```
time ./importGenePanel.pl --data /home/bioinfo/cbioportal/core/src/test/scripts/test_data/study_es_0/data_gene_panel_testpanel1.txt
```
output

```log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/public-portal.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.rolling.RollingFileAppender.activateOptions(RollingFileAppender.java:179)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:809)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:735)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:615)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:502)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:547)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.mskcc.cbio.portal.util.ProgressMonitor.<clinit>(ProgressMonitor.java:53)
	at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:144)
	at org.mskcc.cbio.portal.scripts.ImportGenePanel.main(ImportGenePanel.java:202)
Reading data from:  /home/bioinfo/cbioportal/core/src/test/scripts/test_data/study_es_0/data_gene_panel_testpanel1.txt

Warnings / Errors:
-------------------
0.  Gene panel TESTPANEL1 already exists in the database but is not being used. Overwriting old gene panel data.; 1x
Done.
Total time:  2959 ms


real	0m3.079s
user	0m8.459s
sys	0m0.355s
```

can you please help ?

**Comment by lakhujanivijay** [comment]
Regarding this error:

`java.io.FileNotFoundException: /logs/public-portal.log (No such file or directory)`

I am wondering if I am following [this](https://docs.cbioportal.org/2.1-deployment/pre-build-steps#prepare-the-log-4-j-properties-file) step correctly. 

At above link , it says the following

This file configures logging for the portal. An example file is available within GitHub:
    ```
    cd src/main/resources
    cp log4j.properties.EXAMPLE log4j.properties
    ```
But you must update the following lines with paths that make sense for the systems your build should target.
    ```
    log4j.appender.a.rollingPolicy.FileNamePattern = ${catalina.base}/logs/public-portal.log.%d.gz
    log4j.appender.a.File = ${catalina.base}/logs/public-portal.log
   ```
Which is exactly what I did.

However, when I look at this [link](
https://gitlab.ics.muni.cz/europdx/cbioportal/cbio-public-info/blob/cbbafd5bd112707e7147153628b5bbf96a045389/Pre-Build-Steps.md), I could see something else:

Prepare Property Files
The portal requires two properties files:  one for global configuration (portal.properties) and one for logging (log4j.properties).  Example files are available within GitHub, but you must take the following steps to prepare them.
```
cd src/main/resources
cp portal.properties.EXAMPLE portal.properties
cp log4j.properties.EXAMPLE log4j.properties
```

For more information about the portal.properties file, see the following reference page.

Prepare the log4j.properties File

Update the following lines with paths that make sense for your local system.
```
log4j.appender.a.rollingPolicy.FileNamePattern = /srv/www/sander-tomcat/tomcat6/logs/public-portal.log.%d.gz
log4j.appender.a.File = /srv/www/sander-tomcat/tomcat6/logs/public-portal.log
```

Which one of them is correct ?

**Comment by jjgao** [comment]
@pieterlukasse @sheridancbio could either of you help with this?

I am also wondering why the gene panel data is still imported with the perl code?

**Comment by sheridancbio** [comment]
First thought : it seems like the property ${catalina.base} is not defined for you. I'm not really familiar with running this perl script, so I don't know what is involved here.

If you just want to see the log message output, I would replace these log paths with a complete, absolute path to a directory on your machine where you have write permission, and would avoid the use of variable substitutions like ${catalina.base}

maybe like this:
log4j.appender.a.rollingPolicy.FileNamePattern = /home/your_home_directory_name/public-portal.log.%d.gz
log4j.appender.a.File = /home/your_home_directory_name/public-portal.log

If you want a more in-depth answer, could you provide the exact strings from your logging configuration file, and tell which host you are running this command from and what directories you think are present on that machine which would be an acceptable destination directories for you to be creating log files in?

**Comment by n1zea144** [comment]
@lakhujanivijay Have you solved this issue?  I agree with what @sheridancbio commented - I don't think ${catalina.base} is available to the log4j parser.  If you don't replace ${catalina.base} with a full path as @sheridancbio suggests, you should pass a system property to the JVM in your tomcat startup script, like 
CATALINA_OPTS='... -Dcatalina.base=$CATALINA_BASE'

see [Setting Environment Variables for Tomcat](https://docs.cbioportal.org/2.1-deployment/deploying#set-environment-variables-for-tomcat)
