### ISSUE TITLE
Test on import structure variants failed

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#6338]
got this error. can you please take a look?
```
org.mskcc.cbio.portal.dao.DaoException: Illegal operation on empty result set.

	at org.mskcc.cbio.portal.scripts.TestImportStructuralVariantData.testImportStructuralVariantData(TestImportStructuralVariantData.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLException: Illegal operation on empty result set.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:841)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2674)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2815)
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:431)
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:431)
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:431)
	at org.mskcc.cbio.portal.scripts.TestImportStructuralVariantData.extractStructuralVariant(TestImportStructuralVariantData.java:65)
	at org.mskcc.cbio.portal.scripts.TestImportStructuralVariantData.testImportStructuralVariantData(TestImportStructuralVariantData.java:135)
	... 29 more
```

**Comment by jjgao** [comment]
related to https://github.com/cBioPortal/cbioportal/pull/4057

@khzhu does this happen in the current rc? Or only when you merge it to your branch?

**Comment by khzhu** [comment]
yes. @JJ. @inodb sent me this link which is exactly the same error I got. 
https://travis-ci.org/cBioPortal/cbioportal/jobs/551949140#L2491-L2492

**Comment by inodb** [comment]
This is fixed now, see test rebase PR:

https://github.com/cBioPortal/cbioportal/pull/6339

Seems like something went haywire with merging the seed_mini.sql
