### ISSUE TITLE
Data load when ehcache filesystem cache is set (v3.1.0)

### ISSUE THREAD

**Issue by radzikp** [cBioPortal/cbioportal#6689]
When run this command metaImport.py -s . -o -n -v -jar /.../scripts/target/scripts-3.1.0.jar ****

```
Error message: 
Caused by: java.lang.RuntimeException: Persistence directory already locked by another process: /../temp
at org.ehcache.impl.persistence.DefaultLocalPersistenceService.internalStart(DefaultLocalPersistenceService.java:105)
at org.ehcache.impl.persistence.DefaultLocalPersistenceService.start(DefaultLocalPersistenceService.java:75)
at org.ehcache.core.spi.ServiceLocator.startAllServices(ServiceLocator.java:128)
at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:593)

Caused by: java.lang.RuntimeException: A CacheManager needs to be set before calling this method.
```

Reason:
If ehcache settings are set to use filesystem cache when portal is up and running in the same time  you import data by scripts-3.1.0.jar then you've got the exception.

**Comment by jjgao** [comment]
@mandawilson would #6666 solve this one?
