### ISSUE TITLE
Network tab crashes on mouseover of a gene

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#6704]
Opening the network tab and mousing over a gene highlights but the whole view freezes
![image](https://user-images.githubusercontent.com/5654699/66741324-8d41e100-ee75-11e9-899d-8d3c64863b36.png)

Selecting genes from the list works

An error appears in console:

    cytoscape.renderer.canvas.portal-renderer.js:164 Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (1) is outside the range (0.0, 1.0).
    at CanvasRenderer.CRp.drawNode (https://cbioportal.health-ri.nl/reactapp/network/files/cytoscape.renderer.canvas.portal-renderer.js:164:25)
    at drawElements (https://cbioportal.health-ri.nl/reactapp/network/files/cytoscape.js:19269:17)
    at drawToContext (https://cbioportal.health-ri.nl/reactapp/network/files/cytoscape.js:19325:9)

**Comment by jjgao** [comment]
@j-hudecek we will remove the network tab very soon and replace it with a pathway view.
