### ISSUE TITLE
CDSA Slide viewer tab  broken in Brave browser

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7068]
https://www.cbioportal.org/patient/tissueImage?caseId=TCGA-OR-A5J6&studyId=acc_tcga

```
session.js?bust=1580171060387:14 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at load (https://cancer.digitalslidearchive.org/app/session.js?bust=1580171060387:14:26)
    at https://cancer.digitalslidearchive.org/app/session.js?bust=1580171060387:5:5
    at Object.execCb (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1696:33)
    at Module.check (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:883:51)
    at Module.enable (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1176:22)
    at Module.init (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:788:26)
    at callGetModule (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1203:63)
    at Object.completeLoad (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1717:29)
```

**Comment by jjgao** [comment]
@inodb the tab seems working now...

**Comment by inodb** [comment]
Not working again, might be on their side tho:

```
session.js?bust=1580944894778:14 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at load (https://cancer.digitalslidearchive.org/app/session.js?bust=1580944894778:14:26)
    at https://cancer.digitalslidearchive.org/app/session.js?bust=1580944894778:5:5
    at Object.execCb (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1696:33)
    at Module.check (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:883:51)
    at Module.enable (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1176:22)
    at Module.init (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:788:26)
    at callGetModule (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1203:63)
    at Object.completeLoad (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (https://cancer.digitalslidearchive.org/node_modules/requirejs/require.js:1717:29)
```

**Comment by inodb** [comment]
@dgutman sorry to send another notification here (i removed the comment from the Google Doc).  Does this error mean anything to you? 👆It seems to pop up occasionally for me. I'm not sure if it's on our end or on CDSA side. Maybe we are passing something through `localStorage`? I'll try n look at the code some more if I see it appear again

**Comment by inodb** [comment]
Ah ok figured it out. It seems to be a `Brave browser` issue. Maybe some privacy "feature"
