### ISSUE TITLE
Unable to run front-end under Ubuntu

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7078]
Not sure if this is a documentation issue or if I am missing a step.  I am able to compile and run front-end on Mac OS X, but unable to do so on Ubuntu (under Windows). 

I currently run:

```
yvm use 1.21.1
nvm use 8.12.0
export BRANCH_ENV=master
yarn install --frozen-lockfile
yarn run buildDLL:dev
```
All of the above complete without error.

I then run:

`yarn run start`

and get:

```
yarn run v1.21.1
$ lerna run watch --parallel
lerna notice cli v3.19.0
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run watch"
cbioportal-frontend: internal/util.js:214
cbioportal-frontend:     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
cbioportal-frontend:     ^
cbioportal-frontend: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
cbioportal-frontend:     at Object.promisify (internal/util.js:214:11)
cbioportal-frontend:     at Object.module.exports.pipeline (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:347403)
cbioportal-frontend:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend:     at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:18:298756)
cbioportal-frontend:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend:     at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:321905)
cbioportal-frontend:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend:     at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:320297)
cbioportal-frontend:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend:     at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:319037)
cbioportal-frontend-commons: internal/util.js:214
cbioportal-frontend-commons:     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
cbioportal-frontend-commons:     ^
cbioportal-frontend-commons: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
cbioportal-frontend-commons:     at Object.promisify (internal/util.js:214:11)
cbioportal-frontend-commons:     at Object.module.exports.pipeline (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:347403)
cbioportal-frontend-commons:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend-commons:     at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:18:298756)
cbioportal-frontend-commons:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend-commons:     at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:321905)
cbioportal-frontend-commons:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend-commons:     at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:320297)
cbioportal-frontend-commons:     at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
cbioportal-frontend-commons:     at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:319037)
lerna ERR! yarn run watch exited 1 in 'cbioportal-frontend'
lerna ERR! yarn run watch stderr:
internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:214:11)
    at Object.module.exports.pipeline (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:347403)
    at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
    at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:18:298756)
    at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
    at Object.<anonymous> (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:321905)
    at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
    at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:320297)
    at n (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:2:124)
    at Object.module.exports.Object.defineProperty.value (/home/ecerami/.nvm/versions/node/v8.12.0/lib/node_modules/yarn/bin/yarn.js:24:319037)

lerna ERR! yarn run watch exited 1 in 'cbioportal-frontend'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Tagging @alisman and @Luke-Sikina for possible help :-)

**Comment by ecerami** [comment]
Not sure what was causing this issue.  But, I uninstalled Node on Windows and started with a fresh reset of Ubuntu, and now everything works as described in the README.  Closing.
