### ISSUE TITLE
Docker migration: Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#7284]
Hi,
I am trying to build a database from scratch. While going through the tutorial, I got stuck at step 4 - Migrate database to latest version.

All previous steps worked just fine, I used the following seed: seed-cbioportal_mm10_v2.3.1.sql.gz
(I use this version because seed-cbioportal_mm10_v2.4.0.sql.gz for some reason is not available, 404)

Now trying this:
`docker run --rm -it --net cbio-net \
    -v ${dbPath}/portal.properties:/cbioportal/portal.properties:ro \
    cbioportal/cbioportal:latest \
    migrate_db.py -p /cbioportal/portal.properties -s /cbioportal/db-scripts/src/main/resources/migration.sql`

gives me the following error: 

```
WARNING: This script will alter your database! Be sure to back up your data before running.
Continue running DB migration? (y/n) y
(2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
--> Error connecting to server localhost
Traceback (most recent call last):
  File "/usr/local/bin/migrate_db.py", line 54, in get_db_cursor
    db = portal_properties.database_name)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/migrate_db.py", line 336, in <module>
    main()
  File "/usr/local/bin/migrate_db.py", line 320, in main
    connection, cursor = get_db_cursor(portal_properties)
  File "/usr/local/bin/migrate_db.py", line 66, in get_db_cursor
    raise ConnectionError(message) from exception
ConnectionError: --> Error connecting to server localhost
```

My step 2 - Run mysql with seed database looks like this
```
dbPath=/media/rad/HDD2/cbioportal/
sqlFile=seed-cbioportal_mm10_v2.3.1.sql.gz

# Run mysql with seed database
docker run -d --restart=always \
  --name=cbioDB \
  --net=cbio-net \
  -e MYSQL_ROOT_PASSWORD='password' \
  -e MYSQL_USER=user \
  -e MYSQL_PASSWORD='password' \
  -e MYSQL_DATABASE=cbioportal \
  -v ${dbPath}/db_files/:/var/lib/mysql/ \
  -v ${dbPath}/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro \
  -v ${dbPath}/${sqlFile}:/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
  mysql:5.7

```

My portal.properties includes these rows: 
```
db.host=localhost
db.portal_db_name=cbioportal
db.driver=com.mysql.jdbc.Driver
db.connection_string=jdbc:mysql://localhost/
```

My docker is: Docker version 19.03.6, build 369ce74a3c

Thank you very much for the help!
Cheers

**Comment by NikdAK** [comment]
Ok I found my error!
My portal.properties was wrong: 
1. db.user was = user instead of the defined username  
2. host was set to localhost or 127.0.0.1 instead of cbioDB
