### ISSUE TITLE
study not shown after docker restart container

### ISSUE THREAD

**Issue by likelet** [cBioPortal/cbioportal#7505]
after import my study by following the code from the documentation
```
docker run -it --rm --net cbio-net \
    -v /<path_to_config_file>/portal.properties:/cbioportal/portal.properties:ro \
    -v "<path_to_study_directory>:/study:ro" \
    -v "<path_to_report_folder>:/report" \
    cbioportal/cbioportal:latest \
    metaImport.py -u http://cbioportal-container:8080 -s /study --html=/report/report.html
```
I restart the container by `docker restart ` command. However, the study was not shown in my web page. Did i do something wrong?
thansk for the help 
[report.html.zip](https://github.com/cBioPortal/cbioportal/files/4633215/report.html.zip)

**Comment by n1zea144** [comment]
Hi @likelet I think the importer will not import data if there are warnings without using the -o "override_warning" flag to the metaImport.py script.  Have you check the validation report?  If so, and the warnings are acceptable to you, try using the -o flag.

**Comment by likelet** [comment]
@n1zea144 hi, I add a `-o` parameter in the command, and it does throw an error related to the data format. I will fix the format and let you know once it works.
 BTW, I think this information should be added in the documentation for beginners.  :)

**Comment by likelet** [comment]
by adding  `-o` parameter, it returns the error as follows 
```
#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using /cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar

Checked DB schema version: (expected: 2.12.4) (found: 2.12.4)
Loading cancer types...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
--> Loaded 0 new cancer types.
Done.

Warnings / Errors:
-------------------
0.  Cancer type with id 'stad' already exists. Skipping.; 1x

Warnings / Errors:
-------------------
0.  Cancer type with id 'stad' already exists. Skipping.; 1x
Done.
Total time:  6088 ms

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Checking if Cancer study with identifier gc_xulab_2020 already exists before removing...
Recaching...
Finished recaching...
Cancer study with identifier gc_xulab_2020 does not exist the the database, not removing...
Done.
Total time:  6049 ms

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Recaching...
Finished recaching...

ABORTED!
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Unsupported reference genome
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.run(ImportCancerStudy.java:73)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.main(ImportCancerStudy.java:93)
Caused by: org.mskcc.cbio.portal.dao.DaoException: Unsupported reference genome
at org.mskcc.cbio.portal.dao.DaoCancerStudy.addCancerStudy(DaoCancerStudy.java:327)
at org.mskcc.cbio.portal.util.CancerStudyReader.loadCancerStudy(CancerStudyReader.java:70)
at org.mskcc.cbio.portal.util.CancerStudyReader.loadCancerStudy(CancerStudyReader.java:56)
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.run(ImportCancerStudy.java:57)
... 2 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 156, in <module>
    cbioportalImporter.main(args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 533, in main
    process_directory(jvm_args, study_directory, args.update_generic_assay_entity)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 345, in process_directory
    import_study(jvm_args, study_meta_filename)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 74, in import_study
    run_java(*args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 933, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

```
I tried to add the `genome_build` attribute in the `meta_study.txt` file. But the error still exist.

Then I downloaded the test data set from the repo with name `study_es_0`, however, the test dataset could also  not  pass the importing command
```
docker run -it --rm --net cbio-net \
    -v /backup/zhaoqi/cbioportal/portal.properties:/cbioportal/portal.properties:ro \
    -v "/backup/zhaoqi/cbioportal/study/study_es_0:/study:ro" \
    -v "/backup/zhaoqi/cbioportal/report:/report" \
    cbioportal/cbioportal:latest \
    metaImport.py -o -u http://cbioportal-container:8080 -s /study --html=/report/report.html

```
with the following error 
```

INFO: data_gene_panel_matrix.txt: line 1: This column can be replaced by a 'gene_panel' property in the respective meta file; value encountered: 'gistic'
ERROR: data_gene_panel_matrix.txt: lines [2, 3, 4, (10 more)]: Gene panel ID is not in database. Please import this gene panel before loading study data.; values encountered: ['TESTPANEL1', 'TESTPANEL2']
INFO: data_gene_panel_matrix.txt: Validation of file complete
INFO: data_gene_panel_matrix.txt: Read 20 lines. Lines with warning: 0. Lines with error: 13

INFO: -: Validation complete


#######################################################################
One or more errors reported above. Please fix your files accordingly
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
so could you plz provided a valid test dataset to help me to fix the errors triggered by formating?
thanks for your help.

**Comment by n1zea144** [comment]
@likelet You can find test data here (like study_es_0, _1):
https://github.com/cBioPortal/cbioportal/tree/master/core/src/test/scripts/test_data

**Comment by dippindots** [comment]
@likelet You might also need to import the gene panel before import a certain study. For example, if you found the gene panel information is missing when you try to import the example study, you can run this command (take `study_es_0` as example):
``` 
docker run -it --rm \
   --net cbio-net \
   -v /<path_to_config_file>/portal.properties:/cbioportal/portal.properties:ro \
   -v <path_to_genepanel_file>:/gene_panels/gene_panel.txt:ro \
   cbioportal/cbioportal:latest \
   bash -c 'cd /cbioportal/core/src/main/scripts/ && ./importGenePanel.pl --data /gene_panels/gene_panel.txt'
``` 

Please make sure you replaced `<path_to_config_file>` and `<path_to_genepanel_file>` with an absolute path of your file.

These two gene panel files needs to be imported for `study_es_0`: https://docs.cbioportal.org/2.1.2-deploy-without-docker/load-sample-cancer-study#import-gene-panel-for-sample-study

**Comment by inodb** [comment]
@likelet please let us know of @dippindots suggestion solved the problem. Thank you!

**Comment by likelet** [comment]
Thanks for your reply and sorry for not paste all the errors here.  Except for the error above, there are  several other errors, which I selected as follow:
```
ERROR: meta_gsva_pvalues.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
ERROR: meta_gsva_scores.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
ERROR: data_cancer_type.txt: line 1: column 5: Unknown parent for cancer type 'brca-es0'; value encountered: 'Breast'
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'brca-es0'
ERROR: data_gene_panel_matrix.txt: lines [2, 3, 4, (10 more)]: Gene panel ID is not in database. Please import this gene panel before loading study data.; values encountered: ['TESTPANEL1', 'TESTPANEL2']
```
In my case, I have a study with only mutation and CNV information. The reason I run the example dataset is trying to figure out whether the system works for a new dataset. However, loading an example dataset with too many errors is a little frustrating for me.  Could you plz provide a very simple study which could be directly loaded without handling the errors above.

In addition, for my data, it is hard to understand that even it passes the validation process, it still throws errors in the loading process.
```
Starting validation...

INFO: meta_CNA.txt: Validation of meta file complete

INFO: meta_CNA_log2.txt: Validation of meta file complete

INFO: meta_cancer_type.txt: Validation of meta file complete

INFO: meta_gc_clinical_patient.txt: Validation of meta file complete

INFO: meta_gc_clinical_sample.txt: Validation of meta file complete

WARNING: meta_mutation.txt: Unrecognized field in meta file; value encountered: 'genome_build'
INFO: meta_mutation.txt: Validation of meta file complete

INFO: meta_study.txt: Validation of meta file complete

INFO: cancer_type.txt: Validation of file complete
INFO: cancer_type.txt: Read 1 lines. Lines with warning: 0. Lines with error: 0

INFO: data_gc_clinical_sample.txt: Validation of file complete
INFO: data_gc_clinical_sample.txt: Read 73 lines. Lines with warning: 0. Lines with error: 0

WARNING: data_CNA.txt: lines [2, 3, 4, (21919 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['100287102', '653635', '79501', '(21919 more)']
INFO: data_CNA.txt: Validation of file complete
INFO: data_CNA.txt: Read 21923 lines. Lines with warning: 21922. Lines with error: 0

INFO: data_gc_clinical_data_patient.txt: Validation of file complete
INFO: data_gc_clinical_data_patient.txt: Read 73 lines. Lines with warning: 0. Lines with error: 0

WARNING: data_CNA_log2.txt: lines [2, 3, 4, (21919 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['100287102', '653635', '79501', '(21919 more)']
INFO: data_CNA_log2.txt: Validation of file complete
INFO: data_CNA_log2.txt: Read 21923 lines. Lines with warning: 21922. Lines with error: 0

WARNING: data_mutation_simp.maf: line 1: The recommended column Entrez_Gene_Id was not found. Using Hugo_Symbol for all gene parsing
WARNING: data_mutation_simp.maf: line 1: Including the SWISSPROT column is recommended to make sure that the UniProt canonical isoform is used when drawing Pfam domains in the mutations view
INFO: data_mutation_simp.maf: lines [2, 3, 4, (69099 more)]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; values encountered: ['Intron', 'RNA', '5'UTR', '(4 more)']
WARNING: data_mutation_simp.maf: lines [10, 15, 22, (17873 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['GBP3', 'NBPF9', 'PRG4', '(8758 more)']
WARNING: data_mutation_simp.maf: lines [6900, 32317, 42710, (1 more)]: No Amino_Acid_Change or HGVSp_Short value. This mutation record will get a generic "MUTATED" flag
INFO: data_mutation_simp.maf: Validation of file complete
INFO: data_mutation_simp.maf: Read 86979 lines. Lines with warning: 17877. Lines with error: 0

INFO: case_lists/cases_all.txt: Validation of meta file complete

INFO: case_lists/cases_cnaseq.txt: Validation of meta file complete

INFO: case_lists/cases_cna.txt: Validation of meta file complete

INFO: case_lists/cases_sequenced.txt: Validation of meta file complete

INFO: -: Validation of case list folder complete
INFO: -: Validation complete


#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using /cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar

Checked DB schema version: (expected: 2.12.4) (found: 2.12.4)
Loading cancer types...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
--> Loaded 0 new cancer types.
Done.

Warnings / Errors:
-------------------
0.  Cancer type with id 'stad' already exists. Skipping.; 1x

Warnings / Errors:
-------------------
0.  Cancer type with id 'stad' already exists. Skipping.; 1x
Done.
Total time:  5994 ms

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Checking if Cancer study with identifier gc_xulab_2020 already exists before removing...
Recaching...
Finished recaching...
Cancer study with identifier gc_xulab_2020 does not exist the the database, not removing...
Done.
Total time:  6048 ms

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/cbioportal/scripts/target/scripts-3.3.2-dirty-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Recaching...
Finished recaching...

ABORTED!
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Unsupported reference genome
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.run(ImportCancerStudy.java:73)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.main(ImportCancerStudy.java:93)
Caused by: org.mskcc.cbio.portal.dao.DaoException: Unsupported reference genome
at org.mskcc.cbio.portal.dao.DaoCancerStudy.addCancerStudy(DaoCancerStudy.java:327)
at org.mskcc.cbio.portal.util.CancerStudyReader.loadCancerStudy(CancerStudyReader.java:70)
at org.mskcc.cbio.portal.util.CancerStudyReader.loadCancerStudy(CancerStudyReader.java:56)
at org.mskcc.cbio.portal.scripts.ImportCancerStudy.run(ImportCancerStudy.java:57)
... 2 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by dippindots** [comment]
Hi @likelet , I am wondering that maybe you missed something in this step: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-2-run-mysql-with-seed-database? When we create a database, we also want to import a `seed-database` at the same time, that would import some necessary information about the genome build you choose.
Could you confirm that you added this line?
```bash
-v /<path_to_seed_database>/seed-cbioportal_<genome_build>_<seed_version>.sql.gz:/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
```

**Comment by likelet** [comment]
@dippindots thanks for your suggestion. But I am sure that this step was run at the early stage of the whole process. You can find the container run as one of the follows:

![image](https://user-images.githubusercontent.com/3021506/82390543-90d3c100-9a71-11ea-9e78-5cc11f466e61.png)

my command is 
```
#!/bin/sh
docker run -d --restart=always \
  --name=cbioDB \
  --net=cbio-net \
  -e MYSQL_ROOT_PASSWORD='P@ssword1' \
  -e MYSQL_USER=cbio \
  -e MYSQL_PASSWORD='P@ssword1' \
  -e MYSQL_DATABASE=cbioportal \
  -v /data/sqldb/db_files/:/var/lib/mysql/ \
  -v /backup/zhaoqi/cbioportal/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro \
  -v /backup/zhaoqi/cbioportal/seed-cbioportal_hg19_v2.7.3.sql.gz:/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
  mysql:5.7
```
kind regards.

**Comment by dippindots** [comment]
@likelet Sorry for the inconvenience, could you tell me that can you import the `study_es_0` correctly? Is the problem is about your custom study or both of them?

**Comment by likelet** [comment]
Yes  both of them could not be imported correctly

**Comment by dippindots** [comment]
@likelet Sorry I still cannot reproduce the issue you are facing. I am following the docker document and imported gene panel then import `study_es_0` will have no issue, I guess it's a configuration issue. Please seek for help from here: https://slack.cbioportal.org/. Our group will help you out there. Thanks!

**Comment by likelet** [comment]
well, @dippindots @jjgao @n1zea144 @inodb @sheridancbio   thank you all, I will find further help on slack.
