### ISSUE TITLE
Cannot use metaImport.py with keycloak protected server

### ISSUE THREAD

**Issue by amcpherson** [cBioPortal/cbioportal#7863]
I have set up cbioportal to work with keycloak.  Login to cbioportal works from a browser and after login I can navigate to the api info at:
https://shahcbioportal.org/api/info?pageSize=9999999

However, im not sure how to use metaImport.py to import data, since metaImport.py attempts to connect to the api but is not authorized:

```
:~$ docker run -it --rm --net cbio-net     -v $CBIO/portal.properties:/cbioportal/portal.properties:ro     -v "/home/amcpherson/apollo/:/study:ro"     -v "/home/amcpherson/apollo/report:/report"     cbioportal/cbioportal:latest     metaImport.py -u http://localhost:8081  -s /study --html=/report/report.html -o
Starting validation...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during validation step:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2caf3879b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /api/info?pageSize=9999999 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2caf3879b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 129, in <module>
    exitcode = validateData.main_validate(args)
  File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 5432, in main_validate
    portal_instance = load_portal_info(server_url, logger)
  File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 5046, in load_portal_info
    parsed_json = request_from_portal_api(path, api_name, logger)
  File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 4901, in request_from_portal_api
    response = requests.get(service_url)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /api/info?pageSize=9999999 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2caf3879b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by nr23730** [comment]
If you set up cBioPortal with authentication you need to dump the portal info to your disk instead of accessing it through the web.
Here you will find further information about this: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/example_commands#using-cached-portal-side-data

**Comment by inodb** [comment]
Note that there will be a bug fix in v3.4.11 related to the portal info dump: https://github.com/cBioPortal/cbioportal/pull/7843. Will be released today

**Comment by jjgao** [comment]
@inodb should we close this?

**Comment by inodb** [comment]
@amcpherson this should be fixed by using the portal info dump (see comments above). Let me know if this is still an issue and we can re-open the ticket
