### ISSUE TITLE
Cyclical dependencies

### ISSUE THREAD

**Issue by weberc2-tempus** [cBioPortal/cbioportal#7993]
EDIT: If I revert to version `3.4.8`, then this problem goes away.

I'm getting the following error when I try to deploy via Docker Compose. I've tried both the 3.4.11 and the latest image tags:

```
Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
```

I'm not sure what I could be doing wrong, since the instructions are pretty straight-forward. Googling hasn't been fruitful.

Here are the full logs:

```bashAttaching to cbioportal_container
cbioportal_container           | Using database config:
cbioportal_container           | db.host=cbioportal_database:3306
cbioportal_container           | db.user=cbio_user
cbioportal_container           | db.portal_db_name=cbioportal
cbioportal_container           | db.password=somepassword
cbioportal_container           | Database connection success
cbioportal_container           | Migrating database if necessary...
cbioportal_container           | Everything up to date, nothing to migrate.
cbioportal_container           | Finished.
cbioportal_container           | Running: /bin/sh -c java -Xms2g -Xmx4g -Dauthenticate=noauthsessionservice -Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/ -jar webapp-runner.jar -AmaxHttpHeaderSize=16384 -AconnectionTimeout=20000 --enable-compression /cbioportal-webapp
cbioportal_container           | Connector attributes
cbioportal_container           | property: maxHttpHeaderSize - 16384
cbioportal_container           | property: connectionTimeout - 20000
cbioportal_container           | Adding Context  for /cbioportal-webapp
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.coyote.AbstractProtocol init
cbioportal_container           | INFO: Initializing ProtocolHandler ["http-nio-8080"]
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
cbioportal_container           | INFO: Using a shared selector for servlet write/read
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.catalina.core.StandardService startInternal
cbioportal_container           | INFO: Starting service [Tomcat]
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.catalina.core.StandardEngine startInternal
cbioportal_container           | INFO: Starting Servlet Engine: Apache Tomcat/8.5.51
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.catalina.startup.SetContextPropertiesRule begin
cbioportal_container           | WARNING: [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
cbioportal_container           | Oct 20, 2020 6:07:38 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
cbioportal_container           | INFO: No global web.xml found
cbioportal_container           | Oct 20, 2020 6:07:39 PM org.apache.catalina.core.ContainerBase startInternal
cbioportal_container           | SEVERE: A child container failed during start
cbioportal_container           | java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:931)
cbioportal_container           | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
cbioportal_container           | 	at java.base/java.lang.Thread.run(Unknown Source)
cbioportal_container           | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
cbioportal_container           | 	... 6 more
cbioportal_container           | Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2129)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2067)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2013)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1983)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1936)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1237)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1141)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:776)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
cbioportal_container           | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5063)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	... 6 more
cbioportal_container           | 
cbioportal_container           | Oct 20, 2020 6:07:40 PM org.apache.catalina.core.ContainerBase startInternal
cbioportal_container           | SEVERE: A child container failed during start
cbioportal_container           | java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:931)
cbioportal_container           | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:439)
cbioportal_container           | 	at webapp.runner.launch.Main.main(Main.java:289)
cbioportal_container           | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942)
cbioportal_container           | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
cbioportal_container           | 	at java.base/java.lang.Thread.run(Unknown Source)
cbioportal_container           | Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:931)
cbioportal_container           | 	... 8 more
cbioportal_container           | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
cbioportal_container           | 	... 6 more
cbioportal_container           | Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2129)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2067)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2013)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1983)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1936)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1237)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1141)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:776)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
cbioportal_container           | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5063)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	... 6 more
cbioportal_container           | 
cbioportal_container           | Exception in thread "main" org.apache.catalina.LifecycleException: A child container failed during start
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942)
cbioportal_container           | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:439)
cbioportal_container           | 	at webapp.runner.launch.Main.main(Main.java:289)
cbioportal_container           | Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:931)
cbioportal_container           | 	... 8 more
cbioportal_container           | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942)
cbioportal_container           | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
cbioportal_container           | 	at java.base/java.lang.Thread.run(Unknown Source)
cbioportal_container           | Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
cbioportal_container           | 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
cbioportal_container           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:931)
cbioportal_container           | 	... 8 more
cbioportal_container           | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
cbioportal_container           | 	... 6 more
cbioportal_container           | Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2129)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2067)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2013)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1983)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1936)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1237)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1141)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:776)
cbioportal_container           | 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
cbioportal_container           | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5063)
cbioportal_container           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
cbioportal_container           | 	... 6 more

```

**Comment by pvannierop** [comment]
@jj @ino I also run into this problem all the time. It can be remedied by restarting the docker container which has a chance of success, but it is not compatible with starting up cbioportal reliably.

The root cause is that the spring-security.jwt dependency introduced for the oauth2 functionality defines a org.bouncycastle:bcprov-jdk15on dependency that contains a conflicting class definition as present in org.bouncycastle:bcprov-jdk15 dependency (note missing _on_ suffix). The probabilistic behavior of this problem occurring has to do with how java-vm resolves the classes for a particular invocation (as described [here](https://stackoverflow.com/a/35914143).

There are 2 solutions:
1. Exclude the org.bouncycastle:bcprov-jdk15on dependency from the final cbiportal product.
2. Remove the dependency on spring-security.jwt and use io.jsonwebtoken library that is used in other places of cbioportal backend (I do not know how feasible that is).
