### ISSUE TITLE
UnsatisfiedDependencyException: beans.factory

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#8513]
Hi,
I think one of the recent releases broke something, this study was running without any errors.

I already had this in the meta study, "reference_genome: hg38"

Any ideas?

Thanks

```
INFO: -: Validation complete


#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using /cbioportal/scripts/target/scripts-3.4.17-dirty-SNAPSHOT.jar

Checked DB schema version: (expected: 2.12.6) (found: 2.12.6)
Loading cancer types...

ABORTED!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceDefinitionServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
at org.mskcc.cbio.portal.util.SpringUtil.initDataSource(SpringUtil.java:67)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.load(ImportTypesOfCancers.java:71)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.run(ImportTypesOfCancers.java:62)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.main(ImportTypesOfCancers.java:122)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
... 19 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
... 32 more
Caused by: java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.get(Unknown Source)
at org.cbioportal.service.impl.CancerTypeServiceImpl.getParent(CancerTypeServiceImpl.java:76)
at org.cbioportal.service.impl.CancerTypeServiceImpl.initPrimarySiteMap(CancerTypeServiceImpl.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
... 44 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 147, in <module>
    cbioportalImporter.main(args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 533, in main
    process_directory(jvm_args, study_directory, args.update_generic_assay_entity)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 337, in process_directory
    import_cancer_type(jvm_args, data_filename)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 67, in import_cancer_type
    run_java(*args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 931, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.
```

**Comment by inodb** [comment]
@NikdAK Thanks for reportin! Is it only broken for that specific study? Are you able to reproduce this error with one of the public studies?

**Comment by NikdAK** [comment]
@inodb It is now broken for all of my studies and also for the example one (lgg_ucsf_2014, with added reference_genome: hg19).

I always used this command: 
`docker-compose run cbioportal metaImport.py -s study/lgg_ucsf_2014 -n -o`

The example command never worked for me, giving me another error regarding "Failed to establish a new connection". 
`docker-compose run cbioportal metaImport.py -u http://cbioportal:8080 -s study/lgg_ucsf_2014 -o`

As an outlook, this "beans.factory" is also making the docker-compose installation for mouse impossible, but I will create a new issue for that somewhen :) 

Thank you for your help!

**Comment by inodb** [comment]
fyi @Luke-Sikina did an initial check of this and found that the issue is in:

```
        if (typeOfCancer.getParent().equals(TISSUE)) {
            return typeOfCancer;
        }
        return getParent(allCancerTypes, allCancerTypes.stream().filter(c -> 
            c.getTypeOfCancerId().equals(typeOfCancer.getParent())).findFirst().get());
    }
```

his question:

>Is it possible that the cancer type hierarchy was updated, and there's now a node or branch that is disconnected from the rest of the graph? The code is breaking because .get() explodes if findFirst() finds nothing

**Comment by inodb** [comment]
@NikdAK I'm not able to reproduce this issue with default install of https://github.com/cBioPortal/cbioportal-docker-compose. Is this only when using hg38 seed database?

**Comment by NikdAK** [comment]
@inodb So I found the issue, I forgot to pull the most recent version of docker-compose and due to the hard-coded .env my container was stuck on 3.4.17.

Now with the most recent docker-compose, the container version 3.6.7 is used and everything works without issues. 
(this time 3.6.7 is hard-coded in .env, not sure if this should be changed to be always be the newest version like now 3.6.12)

Anyways, sorry for the trouble and thanks for your help.

**Comment by inodb** [comment]
@NikdAK no worries! Glad you figured it out! The version is actually hardcoded to an old one because we often like to run new releases in production for a while first before disseminating more widely, but we don't really have a clear process at the moment about when we do update the `.env` file
