### ISSUE TITLE
adding a cancer type already loaded throws an exception

### ISSUE THREAD

**Issue by jochemb** [cBioPortal/cbioportal#853]
This exception occurs when adding a new cancer type for the second time.

`
Exception in thread "main" org.mskcc.cbio.portal.dao.DaoException: Duplicate entry 'crc' for key 'PRIMARY'
at org.mskcc.cbio.portal.dao.DaoTypeOfCancer.addTypeOfCancer(DaoTypeOfCancer.java:68)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.load(ImportTypesOfCancers.java:84)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.main(ImportTypesOfCancers.java:60)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'crc' for key 'PRIMARY'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.Util.getInstance(Util.java:386)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.mskcc.cbio.portal.dao.DaoTypeOfCancer.addTypeOfCancer(DaoTypeOfCancer.java:66)
... 2 more
`

**Comment by Andreea-Bican** [comment]
Hello!
I'm willing to help on this one. So, I read the code and it seems for me that the problem comes from here: you are trying to add the same type of cancer, but you've already created a primary key for it.
I need some clarifications in order to fix this.
 Why do you add the same cancer type for the second time? Are there any modifications made or is it added by mistake for many times?
