### ISSUE TITLE
docker-compose mouse: Error parsing HTTP request header + Error creating bean

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#8544]
Hi,
similar to #8513, but occurring during the installation and data validation of a mouse database. 
This also worked without issues before, now even my old non-docker-compose version (based on 3.4.6) does not work anymore. 

During installation (full log attached): 
[dockerbuild.log](https://github.com/cBioPortal/cbioportal/files/6376913/dockerbuild.log)

```
cbioportal-session-database-container | 2021-04-23T15:32:40.967+0000 I INDEX    [thread2] build index done.  scanned 0 total records. 0 secs
cbioportal-container           | Apr 23, 2021 4:40:19 PM org.apache.coyote.http11.Http11Processor service
cbioportal-container           | INFO: Error parsing HTTP request header
cbioportal-container           |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
cbioportal-container           | java.lang.IllegalArgumentException: Invalid character found in method name [h+/tmp/gpon8080&ipv=...]. HTTP method names must be tokens
cbioportal-container           | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:431)
cbioportal-container           | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:503)
cbioportal-container           | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
cbioportal-container           | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
cbioportal-container           | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
cbioportal-container           | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cbioportal-container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
cbioportal-container           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
cbioportal-container           | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cbioportal-container           | 	at java.base/java.lang.Thread.run(Unknown Source)
```

which results in this error message during data uploading:
```

#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using /cbioportal/scripts/target/scripts-3.6.7-dirty-SNAPSHOT.jar

Checked DB schema version: (expected: 2.12.8) (found: 2.12.8)
Loading cancer types...
--> Loaded 1 new cancer types.
Done.
Done.
Total time:  3174 ms


ABORTED!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'expressionEnrichmentUtil': Unsatisfied dependency expressed through field 'sampleService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
at org.mskcc.cbio.portal.util.SpringUtil.initDataSource(SpringUtil.java:67)
at org.mskcc.cbio.portal.scripts.RemoveCancerStudy.run(RemoveCancerStudy.java:55)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.RemoveCancerStudy.main(RemoveCancerStudy.java:96)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
... 18 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
... 31 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
... 44 more
Caused by: java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.get(Unknown Source)
at org.cbioportal.service.impl.CancerTypeServiceImpl.getParent(CancerTypeServiceImpl.java:76)
at org.cbioportal.service.impl.CancerTypeServiceImpl.initPrimarySiteMap(CancerTypeServiceImpl.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.re
[dockerbuild.log](https://github.com/cBioPortal/cbioportal/files/6376910/dockerbuild.log)
flect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
... 56 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 209, in <module>
    cbioportalImporter.main(args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 533, in main
    process_directory(jvm_args, study_directory, args.update_generic_assay_entity)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 344, in process_directory
    remove_study_meta(jvm_args, study_meta_filename)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 95, in remove_study_meta
    run_java(*args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 962, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
Runtim
```eError: Aborting due to error while executing step.
ERROR: 1

**Comment by inodb** [comment]
Let's try to fix #8513 first. Having some issues reproducing that error

**Comment by inodb** [comment]
@NikdAK Since #8513 is fixed now - does that fix this issue as well? Or is this different?

**Comment by NikdAK** [comment]
Looks like this is a different issue.
I reduced a study to 10 mutations for debugging and I think this might be the issue:

`WARNING: mutations_data.txt: lines [2, 3, 4, (7 more)]: Entrez gene id not known to the cBioPortal instance.`
It is discarding all the genes and then crashing due to "No value present". 

Looking into ValidateData.py I found that some gene/entrez sets are empty, which I guess they should not be: 
`{'portal_info_dict': {'portalVersion': '3.6.7-dirty-SNAPSHOT', 'dbVersion': '2.12.8', 'gitBranch': '398542889062a750b9347d867f6f89554ccd9dbd', 'gitCommitId': '398542889062a750b9347d867f6f89554ccd9dbd', 'gitCommitIdDescribe': 'v3.6.7-dirty', 'gitCommitIdDescribeShort': 'v3.6.7-dirty', 'gitCommitMessageFull': 'frontend v3.6.7', 'gitCommitMessageShort': 'frontend v3.6.7', 'gitCommitMessageUserEmail': 'ino@ino.bio', 'gitCommitMessageUserName': 'Ino de Bruijn', 'gitDirty': True}, 'cancer_type_dict': {'pdac': {'name': 'Pancreatic Ductal Adenocarcinoma', 'clinicalTrialKeywords': 'pancreas,pancreas invasive', 'dedicatedColor': 'green', 'shortName': 'pdac', 'parent': 'pancreas'}}, 'hugo_entrez_map': {}, 'alias_entrez_map': {}, 'gene_set_list': [], 'gene_panel_list': {}, 'geneset_version': '', 'entrez_set': set(), '_PortalInstance__species': 'mouse', '_PortalInstance__ncbi_build': '38', '_PortalInstance__genome_build': 'mm10', 'portal_version': '3.6.7-dirty-SNAPSHOT'}`

Maybe  the installation using the mouse seed is not working correctly?

Here you can find my 2 custom mm10 init scripts, the log of my local installation as well as the study.
[debug_example.zip](https://github.com/cBioPortal/cbioportal/files/6390354/debug_example.zip)

**Comment by inodb** [comment]
@SRodenburg is this something you would be interested in helping with?

**Comment by SRodenburg** [comment]
Hi,

I have never seen this error before.
Can you verify whether your genes table is empty, by going to `<cbioportal>/api/genes` API endpoint?
Did you load the mouse seed database correctly?

**Comment by NikdAK** [comment]
Sorry to bother you again again, but are there some news regarding this issue? Thank you very much for the help.

**Comment by NikdAK** [comment]
So I kind of solved the issue for now, apparently only a specific combination of cdgs and seed seems to work.

cdgs.sql: Schema 2.3.1, SQL file with create table statements for portal release 1.7.3
seed: seed-cbioportal_mm10_v2.3.1.sql.gz

All the other seeds and cdgs do not work and end in the error described above.
