### ISSUE TITLE
Mousing over the VAF plot crashes the patient view

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#9332]
https://www.cbioportal.org/patient?caseId=00-010&studyId=prad_fhcrc

Mouse over the VAF plot right next to the tracks to reproduce. Looks like a tooltip issue:

```
Uncaught TypeError: N(...).qtip is not a function
    at SVGGElement.<anonymous> (648.ef8b37a7e63ae3df3e33.chunk.js:2:20267)
    at common.bundle.js?20220222-1545:2:36161
    at pe (common.bundle.js?20220222-1545:2:32552)
    at Array.Y.each (common.bundle.js?20220222-1545:2:36134)
    at Object.j.legend (648.ef8b37a7e63ae3df3e33.chunk.js:2:17289)
    at F (648.ef8b37a7e63ae3df3e33.chunk.js:2:16479)
    at t.value (648.ef8b37a7e63ae3df3e33.chunk.js:2:22473)
    at Ra (common.bundle.js?20220222-1545:2:1967819)
    at Ia (common.bundle.js?20220222-1545:2:1970739)
    at common.bundle.js?20220222-1545:2:1988402
```

**Comment by inodb** [comment]
@onursumer ah good catch - i thought we ran into this a while ago after upgrading https://github.com/cBioPortal/cbioportal-frontend/pull/4056. But seems there are some corner cases that aren't handled

**Comment by inodb** [comment]
Also reported by user: https://groups.google.com/g/cbioportal/c/L_Ca3AEMzOU/m/TRFCbdQVEwAJ
